### ISSUE TITLE
UUID based object buffers

### ISSUE THREAD

**Issue by moda20** [retroburst/log4js-memory-appender#2]
hi !

can the memory appender handle multiple buffers ? something for multiple unrelated log inputs. 

scenario : memory log per request, that needs to die if the request is done or outputted to a file if needed

**Comment by retroburst** [comment]
Hey,

It may be able to do something like that for you, just not out of the box though. You would need to write some kind of wrapper around it and log4js to get that working. It may be easier to write your own logger for your specific use case.
